apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: postgres-external
  namespace: default
spec:
  hosts:
    - {{ .Values.postgres.externalHost }}
  ports:
    - number: {{ .Values.postgres.port }}
      name: tcp-postgres
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS

