apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.muffinCurrency.name }}
  labels:
    app: {{ .Values.muffinCurrency.name }}
spec:
  replicas: {{ .Values.muffinCurrency.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.muffinCurrency.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.muffinCurrency.name }}
    spec:
      containers:
        - name: {{ .Values.muffinCurrency.name }}
          image: {{ .Values.muffinCurrency.image }}
          imagePullPolicy: {{ .Values.muffinCurrency.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.muffinCurrency.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.muffinCurrency.livenessProbe.path }}
              port: {{ .Values.muffinCurrency.containerPort }}
            initialDelaySeconds: {{ .Values.muffinCurrency.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.muffinCurrency.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.muffinCurrency.readinessProbe.path }}
              port: {{ .Values.muffinCurrency.containerPort }}
            initialDelaySeconds: {{ .Values.muffinCurrency.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.muffinCurrency.readinessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.muffinCurrency.name }}
spec:
  type: {{ .Values.muffinCurrency.service.type }}
  selector:
    app: {{ .Values.muffinCurrency.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.muffinCurrency.service.port }}
      targetPort: {{ .Values.muffinCurrency.service.targetPort }}
